(defpackage #:http-protocol
  (:use #:cl)
  (:export #:http-error
           #:http-protocol-error
           #:unsupported-content-coding
           #:unsupported-content-coding-coding
           #:unsupported-operation
           #:unsupported-operation-operation
           #:http-connection-error
           #:http-timeout-error
           #:http-tls-error
           #:http-redirect-error
           #:http-canceled
           #:http-status-error
           #:http-status-error-response
           #:http-status-error-status
           #:http-client-error
           #:http-server-error
           ;; Content-Encoding
           #:decode-content-coding
           #:encode-content-coding
           #:decode-content-codings
           #:encode-content-codings
           #:make-decoding-stream
           #:make-encoding-stream
           #:make-octet-input-stream
           #:make-buffered-binary-input-stream
           #:buffered-binary-input-stream
           #:buffered-stream-source
           #:*http-stream-buffer-size*
           #:copy-stream
           #:prepare-request-content
           #:prepare-request-body
           #:wrap-response-body-stream
           #:body-stream
           #:make-multipart-body
           #:make-multipart-form-stream
           #:build-multipart-parts
           #:parse-content-disposition
           #:content-disposition-filename
           #:slurp-octets
           #:coerce-to-octets
           #:content-coding-supported-p
           #:available-content-codings
           #:default-accept-encoding
           #:parse-content-encoding
           #:normalize-content-coding
           #:*content-coding-systems*
           ;; Client protocol types
           #:http-backend
           #:http-backend-p
           #:http-client
           #:http-client-p
           #:http-client-backend
           #:http-client-base-url
           #:http-client-headers
           #:http-client-cookie-jar
           #:http-client-auth
           #:http-client-timeout
           #:http-client-retry
           #:http-client-max-redirects
           #:http-client-proxy
           #:http-client-pool
           #:http-client-verify
           #:http-file
           #:http-file-p
           #:make-http-file
           #:http-file-filename
           #:http-file-content-type
           #:http-file-content-length
           #:http-file-content
           #:http-file-field-name
           #:http-request
           #:http-request-p
           #:make-http-request
           #:http-request-method
           #:http-request-url
           #:http-request-headers
           #:http-request-content
           #:http-request-data
           #:http-request-files
           #:http-request-params
           #:http-request-timeout
           #:http-request-retry
           #:http-request-max-redirects
           #:http-request-proxy
           #:http-request-cookies
           #:http-request-auth
           #:http-request-range
           #:http-request-accept-encoding
           #:http-request-content-encoding
           #:http-request-decompress
           #:http-request-force-binary
           #:http-request-want-stream
           #:http-request-raise-for-status
           #:effective-auth
           #:authorization-header-value
           #:range-header-value
           #:inject-auth-range-headers
           #:http-response
           #:http-response-p
           #:response-status
           #:response-headers
           #:response-body
           #:response-url
           #:response-http-version
           #:response-cookies
           #:response-history
           #:response-request
           #:response-header
           #:response-as-http-file
           #:ensure-cookie-jar
           #:resolve-cookie-jar
           #:cookie-header-value
           #:inject-cookie-header
           #:merge-response-cookies
           #:backend-name
           #:*http-backend*
           #:*http-client*
           #:with-http-backend
           #:with-http-client
           #:make-http-client
           #:send
           #:send-async
           #:cancel-request
           #:raise-for-status
           ;; Timeout / retry / proxy / pool (urllib3 transport policy)
           #:http-timeout
           #:http-timeout-p
           #:make-http-timeout
           #:timeout-connect
           #:timeout-read
           #:timeout-total
           #:coerce-timeout
           #:effective-timeout
           #:timeout-connect-seconds
           #:timeout-read-seconds
           #:timeout-total-seconds
           #:http-retry
           #:http-retry-p
           #:make-http-retry
           #:retry-total
           #:retry-connect
           #:retry-read
           #:retry-status
           #:retry-allowed-methods
           #:retry-backoff-factor
           #:retry-backoff-max
           #:retry-respect-retry-after
           #:coerce-retry
           #:effective-retry
           #:retry-should-retry-p
           #:retry-delay-seconds
           #:http-proxy-config
           #:http-proxy-config-p
           #:make-http-proxy-config
           #:proxy-config-proxy
           #:proxy-config-no-proxy
           #:proxy-config-use-system-proxy
           #:proxy-config-system-automatic-p
           #:proxy-config-script-url
           #:proxy-config-script-text
           #:*default-proxy-config*
           #:ensure-default-proxy-config
           #:configure-proxy
           #:configure-proxy-script
           #:load-proxy-system
           #:load-proxy-system-platform
           #:evaluate-proxy-script
           #:resolve-system-proxy
           #:use-os-automatic-proxy-p
           #:parse-windows-proxy-server
           #:parse-windows-proxy-override
           #:coerce-proxy-config
           #:resolve-proxy
           #:proxy-next-hop
           #:select-proxy
           #:effective-proxy-config
           #:host-bypassed-p
           #:normalize-no-proxy
           #:hostname-matches-pattern-p
           #:strip-ipv6-brackets
           #:format-host-port
           #:parse-proxy-uri
           #:normalize-proxy-scheme
           #:socks-proxy-scheme-p
           #:http-proxy-scheme-p
           #:proxy-kind
           #:socks-remote-dns-p
           #:http-connection-pool
           #:http-connection-pool-p
           #:*default-connection-pool*
           #:*connection-pool-constructor*
           #:make-connection-pool
           #:ensure-default-connection-pool
           #:pool-acquire
           #:pool-release
           #:pool-discard
           #:pool-clear
           #:connection-alive-p
           #:pool-key
           #:coerce-connection-pool
           #:effective-connection-pool
           #:pooled-body-stream
           #:make-pooled-body-stream
           #:pooled-stream-source
           #:pooled-stream-connection
           #:release-response-connection))

(defpackage #:http
  (:use #:cl #:http-protocol)
  (:shadow #:get #:delete #:trace #:stream)
  (:export #:request
           #:request-async
           #:get
           #:get-async
           #:head
           #:head-async
           #:options
           #:options-async
           #:post
           #:post-async
           #:put
           #:put-async
           #:patch
           #:patch-async
           #:delete
           #:delete-async
           #:trace
           #:connect
           #:with-client
           ;; Re-export common response accessors for DX
           #:response-status
           #:response-headers
           #:response-body
           #:response-header
           #:response-url
           #:response-cookies
           #:response-history
           #:body-stream
           #:stream
           #:stream-async
           #:http-file
           #:http-file-p
           #:make-http-file
           #:http-file-filename
           #:http-file-content-type
           #:http-file-content-length
           #:http-file-content
           #:http-file-field-name
           #:response-as-http-file
           #:*http-stream-buffer-size*
           #:*http-backend*
           #:*http-client*))
